* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
MIXED RT BY modality
  /CRITERIA=CIN(95) MXITER(100) MXSTEP(10) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0,
    ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)
  /FIXED=modality | SSTYPE(3)
  /METHOD=ML
  /PRINT=SOLUTION TESTCOV
  /RANDOM=INTERCEPT modality | SUBJECT(PID) COVTYPE(VC)
  /RANDOM=INTERCEPT modality | SUBJECT(stim) COVTYPE(VC).
